module.exports = {
  bell: "!",
  arrowLeft: "<",
  box: "#",
  calendar: "D",
  check: "✓",
  chevronRight: ">",
  circleInfo: "i",
  clipboardList: "L",
  clock: "T",
  filter: "F",
  handHoldingHeart: "N",
  heartPulse: "H",
  home: "H",
  idCard: "ID",
  locationDot: "P",
  magnifyingGlass: "S",
  notesMedical: "+",
  pen: "P",
  plus: "\u002b",
  shieldHeart: "N",
  user: "U"
};
